# config.toml

# whether to automatically restart and unjail when jailing is detected
execute_unjail = false
# path to unjail script
unjail_script_path = "/data/unjail.sh"

# Slack Webhook URL for sending alerts
slack_webhook_url = "https://hooks.slack.com/services/YOUR/WEBHOOK/URL"
slack_enabled = false

# PagerDuty
pagerduty_routing_key = "YOUR_PAGERDUTY_API_KEY"
pagerduty_enabled = false

# Telegram
telegram_api_key = ""  # obtained via telegram @BotFather user
telegram_rx_chat_ids = [] # chatIds to alert in Telegram
telegram_enabled = false

# defaults to ${HOME}/hl/data/node_logs/status/hourly
base_path = ""

# your validator address
validator_address = "0x000"

# Decide how often you want to view the logs (1 minute recommended)
check_interval = 60
# If the logs show no updates for 5 minutes, the hl-visor (or consensus) should be considered dead.
log_update_interval = 300

# SinceLastSuccess
alert_threshold_success = 40.0

# LastAckDuration
alert_threshold_ack = 0.03
